'use client';

import { Button } from '@/components/ui/Button';
import { Container } from '@/components/layout/Container';
import { Github, FileText, Star, GitFork } from 'lucide-react';
import { motion } from 'motion/react';
import { useEffect, useState } from 'react';

interface GitHubStats {
  stars: number;
  forks: number;
}

export function Hero() {
  const [githubStats, setGithubStats] = useState<GitHubStats>({
    stars: 0,
    forks: 0,
  });

  useEffect(() => {
    // Fetch GitHub stats
    fetch(
      'https://api.github.com/repos/muneebhashone/typescript-backend-toolkit',
    )
      .then((res) => res.json())
      .then((data) => {
        setGithubStats({
          stars: data.stargazers_count || 0,
          forks: data.forks_count || 0,
        });
      })
      .catch(() => {
        // Silently fail, keep default values
      });
  }, []);

  const commands = [
    'pnpm dlx create-tbk-app',
    'select a full-featured preset',
    'cd <project-name>',
    'pnpm dev',
  ];

  return (
    <section className="relative min-h-screen flex items-center overflow-hidden py-20 lg:py-32">
      <Container className="relative z-10">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left Column - Content */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            className="space-y-8"
          >
            {/* Main heading */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="space-y-4"
            >
              <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold leading-tight">
                Build APIs{' '}
                <span className="text-primary">Without the Headache</span>
              </h1>
            </motion.div>

            {/* Subheading */}
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="text-lg sm:text-xl text-slate-300 leading-relaxed max-w-xl"
            >
              Autogenerated docs like FastAPI. Admin dashboard like Django.
              Artisan-like CLI. One schema to rule everything. Type-safe
              everything.
              <br />
              <span className="text-primary font-semibold">
                Express.js, but with superpowers.
              </span>
            </motion.p>

            {/* CTAs */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.4 }}
              className="flex flex-wrap items-center gap-4"
            >
              <Button
                size="lg"
                variant="outline"
                href="https://github.com/muneebhashone/typescript-backend-toolkit"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Github className="w-5 h-5" />
                View on GitHub
              </Button>
              <Button size="lg" variant="outline" href="#features">
                <FileText className="w-5 h-5" />
                Explore Features
              </Button>
            </motion.div>

            {/* GitHub stats */}
            {githubStats.stars > 0 && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.6, delay: 0.5 }}
                className="flex items-center gap-6 text-sm text-slate-400 pt-4"
              >
                <div className="flex items-center gap-2">
                  <Star className="w-4 h-4 fill-yellow-500 text-yellow-500" />
                  <span>{githubStats.stars.toLocaleString()} stars</span>
                </div>
                <div className="flex items-center gap-2">
                  <GitFork className="w-4 h-4" />
                  <span>{githubStats.forks.toLocaleString()} forks</span>
                </div>
              </motion.div>
            )}
          </motion.div>

          {/* Right Column - Terminal */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="relative"
          >
            <div className="terminal">
              <div className="terminal-header">
                <div className="terminal-button terminal-close" />
                <div className="terminal-button terminal-minimize" />
                <div className="terminal-button terminal-maximize" />
                <span className="ml-2 text-sm text-slate-400">Quick Start</span>
              </div>
              <div className="terminal-body">
                {commands.map((command, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.4, delay: 0.5 + index * 0.1 }}
                    className="flex items-center gap-3 mb-3 last:mb-0 group"
                  >
                    <span className="text-primary font-mono">$</span>
                    <span className="text-slate-200 font-mono text-sm flex-1">
                      {command}
                    </span>
                    <button
                      onClick={() => navigator.clipboard.writeText(command)}
                      className="opacity-0 group-hover:opacity-100 transition-opacity text-slate-500 hover:text-slate-300 p-1 rounded hover:bg-slate-800"
                      title="Copy command"
                    >
                      <svg
                        className="w-4 h-4"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                        />
                      </svg>
                    </button>
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Decorative element */}
            <div className="absolute -z-10 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
          </motion.div>
        </div>
      </Container>
    </section>
  );
}
